#! /bin/sh

#WARN=--warnings=all
FORCE=--force
INSTALL=--install
#SYMLINK=--symlink
#MAKE=--make
#DRYRUN=echo

test -z "$SYMLINK" && COPY=--copy
ADDMISSING=${INSTALL+"--add-missing"}

# use autoreconf if possible, just check for version 2+
case `autoreconf --version 2>/dev/null` in
	*"autoreconf (GNU Autoconf) 2."* )
		echo Usable autoreconf found, running
		$DRYRUN autoreconf $WARN $FORCE $INSTALL $SYMLINK $MAKE
		exit $?
	;;
esac

# add files 'config.guess', 'config.sub', 'ltconfig', 'ltmain.sh'
$DRYRUN libtoolize $FORCE $COPY --automake || exit 1

# generate 'aclocal.m4'
$DRYRUN aclocal $FORCE || exit 1

# generate 'config.h.in'
$DRYRUN autoheader $WARN $FORCE || exit 1

#  generate Makefile.in's from Makefile.am's
$DRYRUN automake $WARN $FORCE ${INSTALL+"--add-missing"} $COPY || exit 1

# generate configure from configure.ac
$DRYRUN autoconf $WARN $FORCE || exit 1

if test -n "$MAKE"; then
	$DRYRUN ./configure || exit 1
	$DRYRUN make || exit 1
fi
