#!/bin/bash
# by Behdad Esfahbod -- not copyrighted.

if test "$#" "<" "2"; then
	echo "Usage:
	create_psf [--mirrorrtl] output.sfm font.bdf input1.sfm ...

The --mirrorrtl option causes the RTL glyphs to be mirrored horizontally."
	exit
fi

CLEANUP () {
	rm -f $TEMPPREFIX.*
}

TEMPPREFIX=/tmp/create_psf-$RANDOM

test "$1" = --mirrorrtl && { MIRROR=-m; shift; } || MIRROR=
OUTPUT="$1"
FONT="$2"
shift 2

# Do clean up on INT signal
trap 'CLEANUP; exit 1' INT

echo "Creating font $OUTPUT"

set -e
cat "$@" > $TEMPPREFIX.sfm &&
echo "Extracting glyphs from font $FONT" &&
{ test "$FONT" "!=" "${FONT%.gz}" && zcat "$FONT" || cat "$FONT"; } |
./bicon-bdf2psf.pl $MIRROR -s $TEMPPREFIX.sfm -o $TEMPPREFIX.psf &&
echo "Adding SFM tables to font" &&
psfaddtable $TEMPPREFIX.psf $TEMPPREFIX.sfm ${OUTPUT%.gz} &&
CLEANUP || { CLEANUP; false; }
